config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  root 'home#home'

   get '/about' => 'home#about'
  get '/contact' => 'home#contact'




  resources :problem_categories do
    resources :problem_posts, only: [:new ,:create]
  end
  resources :problem_posts , only: [] do
    resources :comments, only: [:new ,:create,:destroy]
  end
  get '/problem_posts/:problem_post_id/comments/:id' =>  'comments#destroy'

    resources :event_portfolios, only: [:new ,:create,:destroy,:show,:index]


  resources :problem_posts ,only: [:index ,:show,:edit,:update ,:destroy]

  namespace :organization, path: '' do
    resources :organizations, only: [] do
      get :dashboard, on: :collection
    end
       resources :volunteers, only: [:index]
  end

resources :volunteers, only: [:new, :create]
 

  namespace :volunteer, path: '' do
    resources :volunteers, only: [] do
      get :dashboard, on: :collection
    end
  end
  namespace :samaritan do
    resources :events, only: [:new, :create ]
  end
  resources :event , only: [] do
    resources :participants, only: [:new ,:create,:destroy]
  end
resources :events, only: [:show,:index ]

  namespace :admin do
    resources :dashboard, only: [:index]
  end
  

  get 'get_state_for_country/:country', to: 'home#get_state_for_country'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post , class_name: "ProblemPost", foreign_key: "post_id" 
    validates :post_id , presence: true
  validates :body, presence: true , length: { maximum: 255}
  validates :name, presence: true , length: { maximum: 100}

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
has_many :participants , class_name: "Participant",dependent: :destroy


validates :name,  length: { maximum: 60 }, acceptance: true
validates :coordinator_name,  length: { maximum: 30 }, acceptance: true
validates :location,length: { maximum: 255 }, acceptance: true
validates :duration, inclusion: { in: 0..9 } , numericality: true
validates :coordinator_name, length: { maximum: 60 }
validates :coordinator_phone, numericality: true
validates :moto ,length: { maximum: 255 }, acceptance: true
validates :who_can_participate ,length: { maximum: 255 }, acceptance: true
validates :event_cost ,length: { maximum: 50 }, acceptance: true

validates :coordinator_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
validates :coordinator_email, presence: true
validates :coordinator_email, uniqueness: true


  attr_accessor :start_time
end

app/models/event_portfolio.rb
class EventPortfolio < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
   has_many :volunteers, dependent: :destroy
   
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :event , class_name: "Event", foreign_key: "event_id"
	 validates :event_id , presence: true

  validates :name, presence: true , length: { maximum: 100}
  validates :address, presence: true , length: { maximum: 255}
 
  validates :phone, presence: true , length: { maximum: 10}

  validates :name, presence: true , length: { maximum: 50}
  validates :address, presence: true , length: { maximum: 255}
 
 validates_presence_of :phone,   :presence => {:message => 'invalid format of phone no!'},
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }

end

app/models/problem_category.rb
class ProblemCategory < ActiveRecord::Base
has_many :problem_posts , class_name: "ProblemPost", :primary_key => :id ,:dependent => :destroy
validates :category_id , presence: true
  validates :name_category , presence: true , length: { maximum: 255}
end

app/models/problem_post.rb
class ProblemPost < ActiveRecord::Base
belongs_to :category , class_name: "ProblemCategory", foreign_key: "category_id" 
has_many :comments , class_name: "Comment",dependent: :destroy
validates :category_id , presence: true
  validates :title , presence: true , length: { maximum: 255}
  validates :category_name , presence: true , length: { maximum: 255}
  validates :content , presence: true 
  validates :name ,length: {maximum: 100}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_one :organization, dependent: :destroy, autosave: true
  has_many :events, dependent: :destroy
  ROLES = %w(Samaritan Organization Admin)

  def roles=(roles)
    self.roles_mask = self.class.get_roles_mask(roles)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    roles.include?(role)
  end

  def samaritan?
    has_role?('Samaritan')
  end

  def organization?
    has_role?('Organization')
  end

  def admin?
    has_role?('Admin')
  end

  private
  def self.get_roles_mask(roles)
    (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
	 belongs_to :organization

  def full_name
    [first_name,last_name].reject(&:blank?).join(" ")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
layout "problem_post" , only: [:show, :index]
  def index
   @Ievents= Event.page(params[:page]).per(10)
  end
  def show
  @Ievent = Event.find(params[:id])
  @participant = Participant.new( :event_id => @Ievent_id )
  @participants = @Ievent.participants
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
layout "problem_category" , only: [:home,:contact,:about]

layout "problem_category" , only: [:home,:about,:contact]

def home
	@categories=ProblemCategory.all
	 @post = ProblemPost.page(params[:page]).per(4)
	 @events=EventPortfolio.page(params[:page]).per(10)
	 @Ievents=Event.page(params[:page]).per(4)


end
def about
end
def contact

end
def contact
	end
	def about
	end
  def get_state_for_country
    country_object = ISO3166::Country.find_country_by_name(params[:country])
    states = country_object.states.map{|s| [s[1]['name'], s[1]['name']]}
    render json: { success: true, data: states }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_country_names
    ISO3166::Country.all.map{|c| [c.name, c.name]}
  end

  def get_organization_for_select
    Organization.all.map{|o| [o.name, o.id]}
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
 module DeviseHelper
  
 end

app/helpers/event_portfolio_helper.rb
module EventPortfolioHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  ALERT_TYPES = [:danger, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                               msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/participant_helper.rb
module ParticipantHelper
end

app/helpers/post_categories_helper.rb
module PostCategoriesHelper
end

app/helpers/problem_posts_helper.rb
module ProblemPostsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/home/about.html.erb
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">About
                        <strong>Being Samaritan</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">

                    

                    <img class="img-responsive img-border-left" src="/assets/problemcategory/about.jpeg" alt="">

                </div>
                <div class="col-md-6">
                    <p>This is a great place to write about problems you see around you and don't know how to help</p>
                    <p>We club Ngo's at one place so that easy consultation and for sure solution can be found for issues of our society</p>
                    <p>Help NGo's by being part of it or may be not.Initiate your own events and get volunteers for it from all over your city</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Our
                        <strong>Team</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-sm-4 text-center">

                   

                    <img class="img-responsive" src="assets/problemcategory/sonia.jpg" alt="">

                    <h3>Sonia Goplani<br>
                        <small>Developer</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">

                    

                    <img class="img-responsive" src="assets/problemcategory/yogi.jpg" alt="">

                    <h3>Yogendra Pratap singh
                        <small>Developer</small>
                    </h3>
                </div>
                <div class="col-sm-4 text-center">

                    

                    <img class="img-responsive" src="assets/problemcategory/vaibhav.jpg" alt="">

                    <h3>Vaibhav Kanak<br>
                        <small>Designing and Documentation</small>
                    </h3>
                </div>
                 <div class="col-sm-4 text-center">

                   
                    <img class="img-responsive" src="assets/problemcategory/shubham.jpg" alt="">

                    <h3>Shubham Lakhotia
                        <small>Designing and Documentation</small>
                    </h3>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <!-- /.container -->


    
   


    <!-- jQuery -->
    <script src="js/jquery.js"></script>

   
</body>

</html>

app/views/home/contact.html.erb
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                        <strong>Being Samaritan</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-8">
                    <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
                    

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAV-fWdgpwUDbuzff59Wxdstn2FMpp6hCE
    &q=Rani+Sati+indore,Madhya+Pradesh" allowfullscreen>
</iframe>


                </div>
                <div class="col-md-4">
                    <p>Phone:
                        <strong>7566333308</strong>
                    </p>
                    <p>Email:
                        <strong><a href="mailto:name@example.com">sonia.goplani779@gmail.com</a></strong>
                    </p>
                    <p>Address:
                        <strong>House no. 8
                            <br>Joy Builders Colony</strong>
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

       

app/views/home/home.html.erb
<div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="assets/problemcategory/scroll-1" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="assets/problemcategory/scroll-2" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="assets/problemcategory/scroll-3" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Want to be a part</small>
                    </h2>
                    <h1 class="brand-name"><a href="/users/sign_up">REGISTER YOUR NGO WITH US>
                    </a>
                     </h1>
                    <hr class="tagline-divider">
                    <h2>
                        <% if current_user.present? && current_user.organization? %>
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                  <% else %>
                    <%= link_to 'Login', new_user_session_path %>
                  <% end %>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Tell us about a problem you saw around
                        <strong>Write Blog</strong>
                    </h2>
                    <hr>
                     <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            
                        <% @categories.limit(4).each do |c| %>
                        <ul class="list-unstyled">
                        <li>
                    <%= link_to c.name_category , new_problem_category_problem_post_path(c.id)%>
                        </li>
                         </ul>
                        <% end %>
                        </div>
                      <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            
                            <% @categories.last(4).each do |c| %>
                            <ul class="list-unstyled">
                            <li>
                        <%= link_to c.name_category , new_problem_category_problem_post_path(c.id)%>
                            </li>
                            </ul>
                            <%end%>
                        </div>
                        <!-- /.col-lg-6 -->       
                        </div>
            
                </div>
            </div>
        </div>
    </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Want to be a volunteer of NGO in your city
                        <strong><a href =/volunteers/new>Register Here</a> </strong>
                    </h2>
                    <hr>
                    
                    <p align="center">Invest your leisure time in uplifting this society <br>by shaking hands with active NGO's of your city.<br>
                    Because if we won't who will??</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Want to initiate your event in your city
                        <strong>
                         <% if current_user.present? && current_user.samaritan? %>
                      <%= link_to 'Initiate Event', new_samaritan_event_path %>
                      <%else%>
                        <a href =/users/sign_up>Sign_up(as a Samaritan)</a> 
                         <%end%>
                        </strong><br><br>
                        <strong>
                         <% if current_user.present? && current_user.samaritan? %>
                         <%= link_to 'Logout', destroy_user_session_path %>
                             <%else%>
                             Already a member??  <%= link_to 'Login', new_user_session_path %>
                             <%end%>

                         </strong>
                    </h2>
                    <hr>
                    
                    <p align="center">Initiate events in your city for welfare of  society and surrounding.<br>We will help you get volunteers for your event.<br>from all over city.
                    </p>
                </div>
            </div>
        </div>
        


        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                     
                   <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Wrapper for slides -->
         <ul class="nav nav-pills nav-justified">
            <li data-target="#myCarousel" data-slide-to="0" class="active"><a href="#">Problem Posts<small>By you</small></a></li>
            <li data-target="#myCarousel" data-slide-to="1"><a href="#">News<small>Events done by NGO's</small></a></li>
            <li data-target="#myCarousel" data-slide-to="2"><a href="#">Events<small>Upcoming events in your city</small></a></li>
           
        </ul>
        <div class="carousel-inner">
            <div class="item active">
                <img src="/assets/problemcategory/page1.jpg">
                <div class="carousel-caption">
                    <h3>
                        </h3>
                    <p>
                    <ul class="recent-posts">
                    <% @post.each do |y| %>
                    <div class="post-preview">
                    
                        <h2 class="post-title">
                           <li> <%=link_to y.title , problem_post_path(y.id)%></li>
                        </h2>
                        <h3 class="post-subtitle">
                            
                        </h3>
                   
                        <p class="post-meta">Posted by  <%=y.name%><br> on <%= y.created_at.strftime("%d/%m/%Y %I:%M %p") %>
                        </p>
                        <br>
                    
                    </div>
                    <%end%>
                       <li>
                        <%=link_to "View all", problem_posts_path,
                        :class =>"btn btn-primary"%> 
                       </li>
               
                     </ul>
                    </p>
                </div>
            </div>
            <!-- End Item -->
            <div class="item">

                <img src="/assets/problemcategory/page4.jpg">
                <div class="carousel-caption">
                    <h3>
                        NEWS</h3>
                     <ul class="recent-posts">
                        <% @events.each do |event| %>
                     <div class="post-preview">
                 
                        <h3 class="post-title">
                         <li>  <%=link_to event.event_name , event_portfolio_path(event.id)%>  </li>
                        </h3>
                        <h4>BY: <%= event.organization_name %>
                            on <%= event.event_date.strftime("%d/%m/%Y") %>
                        </h4>
                  
                     <br>
                     
               </div>
                  <%end%>
                 <li>
                 <%=link_to "View all", event_portfolios_path,
                        :class =>"btn btn-primary"%> 
              </li>
               
            </ul>
                </div>
            </div>
            <!-- End Item -->
            <div class="item">

                <img src="/assets/problemcategory/page3.jpg">
                <div class="carousel-caption">
                    <h3>
                        Upcoming Events
                    </h3>
                    <ul class="recent-posts">
                
                        <% @Ievents.each do |event| %>
                     <div class="post-preview">
                 
                        <h3 class="post-title">
                         <li>  <%=link_to event.name , event_path(event.id)%> 

                            <%= event.scheduled_at.strftime("%d/%m/%Y %I:%M %p")%> </li>
                        </h3>
                        <h4>At: <%= event.location %><br>
                            ,  Contact: <%= event.coordinator_name%>(<%= event.coordinator_phone%>)
                        </h4>
                  
                     <br>
                     
                   </div>
                  <%end%>
                 <li>
                 <%=link_to "View all", events_path,
                        :class =>"btn btn-primary"%> 
                 </li>
               
            </ul>
                </div>
            </div>
           
        </div>
        <!-- End Carousel Inner -->
       
    </div>
    <!-- End Carousel -->



                </div>
            </div>
        </div>       

   
      
</div>

        

    

    
    

    