config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  root 'home#home'

   get '/about' => 'home#about'
  get '/contact' => 'home#contact'




  resources :problem_categories do
    resources :problem_posts, only: [:new ,:create]
  end
  resources :problem_posts , only: [] do
    resources :comments, only: [:new ,:create,:destroy]
  end
  get '/problem_posts/:problem_post_id/comments/:id' =>  'comments#destroy'

    resources :event_portfolios, only: [:new ,:create,:destroy,:show,:index]


  resources :problem_posts ,only: [:index ,:show,:edit,:update ,:destroy]

  namespace :organization, path: '' do
    resources :organizations, only: [] do
      get :dashboard, on: :collection
    end
       resources :volunteers, only: [:index]
  end

resources :volunteers, only: [:new, :create]
 

  namespace :volunteer, path: '' do
    resources :volunteers, only: [] do
      get :dashboard, on: :collection
    end
  end
  namespace :samaritan do
    resources :events, only: [:new, :create ]
  end
  resources :event , only: [] do
    resources :participants, only: [:new ,:create,:destroy]
  end
resources :events, only: [:show,:index ]

  namespace :admin do
    resources :dashboard, only: [:index]
  end
  

  get 'get_state_for_country/:country', to: 'home#get_state_for_country'
end

app/models/problem_post.rb
class ProblemPost < ActiveRecord::Base
belongs_to :category , class_name: "ProblemCategory", foreign_key: "category_id" 
has_many :comments , class_name: "Comment",dependent: :destroy
validates :category_id , presence: true
  validates :title , presence: true , length: { maximum: 255}
  validates :category_name , presence: true , length: { maximum: 255}
  validates :content , presence: true 
  validates :name ,length: {maximum: 100}

end

app/controllers/problem_posts_controller.rb
class ProblemPostsController < ApplicationController
layout "problem_post" 


def show
@post = ProblemPost.find(params[:id])
@comment = Comment.new( :post => @post )
@comments = @post.comments
    
end
def index
  @post = ProblemPost.page(params[:page]).per(10)
  
end 
def new

  @category=ProblemCategory.find(params[:problem_category_id])
  @post=ProblemPost.new
    

end
def create 
     @category=ProblemCategory.find(params[:problem_category_id])
   @post=ProblemPost.new(post_params)
   @post.category_id = params[:problem_category_id] 
  
   respond_to do |format|
     
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
end
def show_comment_form
   render :partial=>"problem_posts/comment"
end
private
def post_params
  params.require(:problem_post).permit(:title,:category_name,:category_id,:content ,:name)
end
end

app/helpers/problem_posts_helper.rb
module ProblemPostsHelper
end

app/views/problem_posts/_comments.html.erb
<div class="container">
	<div class="row">
	<!-- Contenedor Principal -->
    <div class="comments-container">
		<h1>Comments </h1>

		<ul id="comments-list" class="comments-list">
			<li>
				<div class="comment-main-level">
				<% Comment.where(post_id: @post.id).each do |y| %>
					<!-- Avatar -->
					<div class="comment-avatar"><img src="http://i9.photobucket.com/albums/a88/creaticode/avatar_1_zps8e1c80cd.jpg" alt=""></div>
					<!-- Contenedor del Comentario -->
					<div class="comment-box">
						<div class="comment-head">
							<h6 class="comment-name by-author">"<%=y.name%></h6>
							<span><%= y.created_at.strftime("%d/%m/%Y %I:%M %p") %> </span>
							<i class="fa fa-pencil-square-o "></i>

							<i class="fa fa-trash-o"><%= link_to 'delete', problem_post_comment_path(@post.id,y.id), :method => :delete %> </i> 
							<i class=" fa fa-comment "></i>	

						</div>
						<div class="comment-content">
							<%=y.body%>
						</div>
					</div>
					<%end%>
				</div>
				
			</li>
		</ul>
	</div>
	</div>
	</div>

app/views/problem_posts/_form.html.erb
<%= form_for [@category, ProblemPost.new] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
    </div><br>
    <div class="field">
        <%= f.label :category %><br>
        <%= f.text_field  :category_name,
        :value=> @category.name_category, :readonly => true %>
    </div><br>
    <div class="field">
         <%= f.hidden_field  :category_id, :value=>@category.id%>
    </div>
    <div class="field">
         <%= f.label :content %><br>
         <%= f.cktext_area :content %>
    </div><br>
  
    <div class="field">
         <%= f.label :name %><br>
         <%= f.text_field :name %>
    </div><br>
  
    <div class="actions">
          <%= f.button(type: 'submit', class: "btn btn-primary") do %>
          <i class="icon-ok icon-white"> Save</i>
     <% end %>
     </div>
  </div>
<% end %>

app/views/problem_posts/_rplycomment.html.erb
	<ul class="comments-list reply-list">
					<li>
						<!-- Avatar -->
						<div class="comment-avatar"><img src="http://i9.photobucket.com/albums/a88/creaticode/avatar_2_zps7de12f8b.jpg" alt=""></div>
						<!-- Contenedor del Comentario -->
						<div class="comment-box">
							<div class="comment-head">
								<h6 class="comment-name"><%=y.name%></h6>
								<span><%= y.created_at.strftime("%d/%m/%Y %I:%M %p") %></span>
								<i class="fa fa-reply"></i>
								<i class="fa fa-heart"></i>
							</div>
							<div class="comment-content">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit omnis animi et iure laudantium vitae, praesentium optio, sapiente distinctio illo?
							</div>
						</div>
					</li>
					</ul>

app/views/problem_posts/index.html.erb
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('assets/problempost/posts.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Problem Posts</h1>
                        <hr class="small">
                        <span class="subheading">By someone between you</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <% @post.each do |y| %>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            <%=link_to y.title , problem_post_path(y.id)%>
                        </h2>
                        <h4 class="post-subtitle">
                           category: <%= link_to ProblemCategory.find(y.category_id).name_category, problem_category_path(y.category_id) %>
                        </h4>
                    </a>
                    <p class="post-meta">Posted by  <%=y.name%><br> on <%= y.created_at.strftime("%d/%m/%Y %I:%M %p") %></p>
                     <br>
                     <%=link_to "Read More", problem_post_path(y.id),
                        :class =>"btn btn-primary"%> 
               </div>
                  <%end%>
                <hr>
              
                <!-- Pager -->
                <ul class="pager">
                    <li>
                    <%= link_to_previous_page @post, 'Previous Page' %>
                    <%= link_to_next_page @post, 'Next Page' %>

                    </li>
                </ul>
            </div>

        </div>
    </div>

    <hr>

app/views/problem_posts/new.html.erb
<!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/assets/problempost/home.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Be a Change</h1>
                        <hr class="small">
                        <span class="subheading">Write about problems you saw around</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
<h1 align="center">New Blog</h1>
<br>

<%= render 'form' %>

app/views/problem_posts/show.html.erb
<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/assets/problempost/post.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1></h1>
                        <hr class="small">
                        <span class="subheading"></span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            <%= @post.try(:title) %>
                        </h2>
                        
                    </a>
                    <p class="post-meta">Posted by <a href="#"><%=@post.try(:name)%></a>  <br>on <%= @post.created_at.strftime("%d/%m/%Y %I:%M %p") %></p>
                </div>

                <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p><%= raw(@post.try(:content)) %></p>
                </div>
            </div>
        </div>
     <%= form_for [@post, Comment.new] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="well">
  <h4>Leave a Comment:</h4>
  <div class="field">
     <%= f.hidden_field  :post_id, :value=>@post.id%>
  </div>

  <div class="field">
    <%= f.label :Text %><br>
    <%= f.text_area :body %>
  </div>
  
  <div class="field">
    <%= f.label :Name %><br>
    <% if user_signed_in? && current_user.organization?%>
     <%= f.text_field :name,:value=> current_user.organization.name, :readonly => true %>
     <% else%>
    <%= f.text_field :name %>
    <%end%>
  </div>
 
  <div class="actions">
    <%= f.button(type: 'Post', class: "btn btn-primary") do %>
    <i class="icon-ok icon-white"> Save</i>
<% end %>
  </div>
  </div>
<% end %>

  
<%= render 'comments', :collection => @post.comments %>
    </article>
                <hr>

  